/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author apaol
 */
public class RobotsInfo extends javax.swing.JFrame {

    /**
     * Creates new form RobotsInfo
     */
    public RobotsInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Grid_Panel = new javax.swing.JPanel();
        Predecesor_2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Predecesor_1 = new javax.swing.JButton();
        Estado_Txt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 15, 34));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Grid_Panel.setMaximumSize(new java.awt.Dimension(780, 620));
        Grid_Panel.setMinimumSize(new java.awt.Dimension(780, 620));
        Grid_Panel.setName(""); // NOI18N
        Grid_Panel.setLayout(new java.awt.GridLayout(20, 20));
        jPanel1.add(Grid_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 950, 950));

        Predecesor_2.setBackground(new java.awt.Color(255, 255, 255));
        Predecesor_2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        Predecesor_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chip.png"))); // NOI18N
        Predecesor_2.setText("Buscar");
        Predecesor_2.setToolTipText("");
        Predecesor_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Predecesor_2.setBorderPainted(false);
        jPanel1.add(Predecesor_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 790, 170, 90));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(56, 0, 0, 2));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 20, 710));

        Predecesor_1.setBackground(new java.awt.Color(255, 255, 255));
        Predecesor_1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        Predecesor_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robot.png"))); // NOI18N
        Predecesor_1.setText("Buscar");
        Predecesor_1.setToolTipText("");
        Predecesor_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Predecesor_1.setBorderPainted(false);
        jPanel1.add(Predecesor_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 170, 90));

        Estado_Txt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        Estado_Txt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Estado_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RobotsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RobotsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RobotsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RobotsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RobotsInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estado_Txt;
    private javax.swing.JPanel Grid_Panel;
    private javax.swing.JButton Predecesor_1;
    private javax.swing.JButton Predecesor_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public JPanel getGenes_TXT() {
        return jPanel2;
    }

    public JPanel getGrid_Panel() {
        return Grid_Panel;
    }

    public JButton getPredecesor_2() {
        return Predecesor_2;
    }

    public JButton getPredecesor_1() {
        return Predecesor_1;
    }
    
}
