/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;

/**
 *
 * @author apaol
 */
public class MenuGeneraciones extends javax.swing.JFrame {
    
    private int CantidadGeneraciones = 0;
    private int GeneracionesInt = 0;
    private int RobotsInt = 0;
    /**
     * Creates new form MenuGeneraciones
     */
    public MenuGeneraciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        Generaciones = new javax.swing.JSpinner();
        Robot = new javax.swing.JSpinner();
        Seleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info_Txt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busqueda de robots");
        setMaximumSize(new java.awt.Dimension(1254, 870));
        setMinimumSize(new java.awt.Dimension(1254, 870));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Buscar.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buscar.setEnabled(false);
        Buscar.setLabel("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 160, 40));

        Generaciones.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        Generaciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel1.add(Generaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 100, 40));

        Robot.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        Robot.setModel(new javax.swing.SpinnerNumberModel());
        Robot.setEnabled(false);
        jPanel1.add(Robot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 100, 40));

        Seleccionar.setBackground(new java.awt.Color(255, 255, 255));
        Seleccionar.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        Seleccionar.setText("Seleccionar");
        Seleccionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 160, 40));

        Info_Txt.setColumns(20);
        Info_Txt.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Info_Txt.setRows(5);
        Info_Txt.setToolTipText("");
        Info_Txt.setSelectionColor(new java.awt.Color(37, 75, 151));
        jScrollPane1.setViewportView(Info_Txt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 250, 730));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.1.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        this.RobotsInt = (Integer) Robot.getValue();
    }//GEN-LAST:event_BuscarActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
        this.GeneracionesInt = (Integer) Generaciones.getValue();
    }//GEN-LAST:event_SeleccionarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGeneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGeneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGeneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGeneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGeneraciones().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JSpinner Generaciones;
    private javax.swing.JTextArea Info_Txt;
    private javax.swing.JSpinner Robot;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JButton getBuscar() {
        return Buscar;
    }

    public JButton getSeleccionar() {
        return Seleccionar;
    }

    public JSpinner getGeneraciones() {
        return Generaciones;
    }
    
    public JSpinner getRobot() {
        return Robot;
    }

    public int getGeneracionesInt() {
        return GeneracionesInt;
    }

    public int getRobotsInt() {
        return RobotsInt;
    }

    public JTextArea getInfo_Txt() {
        return Info_Txt;
    }



    public JLabel getjLabel1() {
        return jLabel1;
    }
    
    
    
}
